import pandas as pd

data = pd.read_csv("./empleados.csv")
print(data)
print("\n")
filtro=data.head(10)
print(filtro)
print("\n")
filtro1=data["nombres"].head(10)
print(filtro1)
print("\n")
filtro2=data[["nombres","salario"]].tail(5)
print(filtro2)
print("\n")
filtro3=data.head(20).describe()
print(filtro3)
print("\n")
filtro4=data[data["edad"]<30].head(20)
print(filtro4)
print("\n")
filtro5=filtro4.dropna()
print("\n")
print(filtro5)
print("\n")
filtro6=data.fillna({"cargo":"sinNaN"})
print(filtro6)
print("\n")