print("Hola soy Valeria")
print("Me encanto el arroz chino VMC")
print("Hola soy Jimena")
print("me encanto el arroz chino JSG")
print("hola soy Daniela")
print("no me gustó el arroz china dac")
print("Hola soy Daniela")
print("me encanto el arroz chino dot")
